Airlines/Controllers/PlaatsController.cs
using Airlines.ViewModels;
using AutoMapper;
using Domains.Entities;
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Interfaces;

namespace Airlines.Controllers
{
    public class PlaatsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IPlaatsService _plaatsService;
        public PlaatsController(IPlaatsService plaatsService, IMapper mapper)
        {
            _plaatsService = plaatsService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var lstPlaatsen = await _plaatsService.GetAllAsync();
                Console.WriteLine(lstPlaatsen);
                List<PlaatsVM> lstPlaatsVM = null;//? of gwn op null zetten
                if (lstPlaatsen != null)
                {
                    Console.WriteLine("test1");
                    lstPlaatsVM = _mapper.Map<List<PlaatsVM>>(lstPlaatsen);
                    return View(lstPlaatsVM);
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "Er is een fout opgetreden");
            }
            return View();
        }
    }
}

Airlines/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gilwe Airlines</title>
    <link rel="stylesheet" href="/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav>
                <div>
                    <a asp-area="" asp-controller="Home" asp-action="Index"><img class="logo" src="~/images/Geluwe airlines blauw.jpg" alt="Gilwe Airlines Logo"/></a>
                    <a asp-area="" asp-controller="Plaats" asp-action="Index">Vluchten</a>
                    <a asp-area="" asp-controller="AanbiedBestemmingen" asp-action="Index">Alle bestemmingen</a>
                    @await Html.PartialAsync("_SelectCulture")
                    <partial name="_LoginPartial" />
                </div>
        </nav>
    </header>
    <div>
        <main>
            @RenderBody()
        </main>
    </div>
    <footer>
        <div>
            &copy; 2025 - Airlines <!-- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>-->
        </div>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Airlines/Views/Shared/_SelectCulture.cshtml
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> locOptions

@{
    // Represents the feature that provides the current request's culture information. (zie cookie culture wordt uitgelezen als deze aanwwezig is anders http-header)
    //De middleware stelt de huidige cultuur en UI-cultuur in, die later in de applicatie beschikbaar zijn via IRequestCultureFeature.

    var currentRequestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = locOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var responseUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" :
        $"~{Context.Request.Path.Value}";
}

<div class="language-selector">
    <form id="selectLanguage" asp-controller="Home"
          asp-action="SetAppLanguage" asp-route-returnUrl="@responseUrl"
          method="post" role="form">
        <label for="lang">@Localizer["Select Language"]</label>
        <select id="lang" name="lang" class="setLang"
                asp-for="@currentRequestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems"
                onchange="this.form.submit()">
        </select>
    </form>
</div>