Airlines/Controllers/PlaatsController.cs
using Airlines.ViewModels;
using AutoMapper;
using Domains.Entities;
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Interfaces;

namespace Airlines.Controllers
{
    public class PlaatsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IPlaatsService _plaatsService;
        public PlaatsController(IPlaatsService plaatsService, IMapper mapper)
        {
            _plaatsService = plaatsService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var lstPlaatsen = await _plaatsService.GetAllAsync();
                Console.WriteLine(lstPlaatsen);
                List<PlaatsVM> lstPlaatsVM = null;//? of gwn op null zetten
                if (lstPlaatsen != null)
                {
                    Console.WriteLine("test1");
                    lstPlaatsVM = _mapper.Map<List<PlaatsVM>>(lstPlaatsen);
                    return View(lstPlaatsVM);
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "Er is een fout opgetreden");
            }
            return View();
        }
    }
}

Airlines/Controllers/VluchtController.cs
using Airlines.ViewModels;
using AutoMapper;
using Domains.Entities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using Services.Interfaces;

namespace Airlines.Controllers
{
    public class VluchtController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IPlaatsService _plaatsService;
        private readonly IVluchtService _vluchtService;
        private readonly IZitplaatsService _zitplaatsService;
        public VluchtController(IPlaatsService plaatsService, IVluchtService vluchtService, IMapper mapper, IZitplaatsService zitplaatsService)
        {
            _plaatsService = plaatsService;
            _vluchtService = vluchtService;
            _mapper = mapper;
            _zitplaatsService = zitplaatsService;
        }
        [HttpPost]
        public async Task<IActionResult> Index(DateTime StartDate, DateTime EndDate, string vertrek, string bestemming)
        {
            try
            {
                Console.WriteLine(vertrek);
                Console.WriteLine(bestemming);
                
                int vertrekPlaatsId = _plaatsService.GetByNaamAsync(vertrek).Result.PlaatsId;
                int bestemmingId = _plaatsService.GetByNaamAsync(bestemming).Result.PlaatsId;

                var lstVluchten = await _vluchtService.GetNormaleVluchtenTussenPlaatsenTussenDatums(vertrekPlaatsId, bestemmingId, StartDate, EndDate);

                
                List<VluchtVM> lstVluchtVM = null;
                if(lstVluchten != null)
                {
                    lstVluchtVM = _mapper.Map<List<VluchtVM>>(lstVluchten);

                    List<VluchtMetOverstappenVM> lstVluchtMetOverstappenVM = new List<VluchtMetOverstappenVM>();
                    foreach (VluchtVM vlucht in lstVluchtVM)
                    {
                       VluchtMetOverstappenVM vluchtMetOverstappenVM = new VluchtMetOverstappenVM();
                        vluchtMetOverstappenVM.GewoneVlucht = vlucht;
                        var lstVanOverstapVluchten = await _vluchtService.GetOverstappenVanVlucht(vlucht.VluchtId);
                        vluchtMetOverstappenVM.OverstapVluchten = _mapper.Map<List<VluchtVM>>(lstVanOverstapVluchten);
                        var aantalBeschikbareZitplaatsen = await _zitplaatsService.TelAantalBeschikbareZitplaatsenVoorVlucht(vlucht.VluchtId);

                       vluchtMetOverstappenVM.AantalBeschikbarePlaatsen = aantalBeschikbareZitplaatsen;

                        lstVluchtMetOverstappenVM.Add(vluchtMetOverstappenVM);  
                    }



                    return View(lstVluchtMetOverstappenVM);

                }
                


            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Er is een fout opgetreden");
            }
            return View();
           
        }
    }
}

Airlines/Views/Plaats/Index.cshtml
@model IEnumerable<Airlines.ViewModels.PlaatsVM>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="/css/plaatsen.css" asp-append-version="true" />
<link rel="stylesheet" href="/css/plaatsKnoppen.css" asp-append-version="true" />
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css" />
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js"></script>
<div class="blokPagina">
<h1>Welke vluchten wenst u?</h1>
<h2>Kies jouw vertrekplaats</h2>
<br/>
<div class="radio-input">
    @foreach (var item in Model)
    {
        <label>
                    <input value="@item.Naam" name="vertrekKeuze" id="@item.Naam-Vertrek" type="radio" class="city-input" />
            <span>@item.Naam</span>
        </label>
    }
     
</div>
<br />

<h2>Kies jouw bestemming</h2>
<br />
<div class="radio-input">
        @foreach (var item in Model)
        {
        <label>
            <input value="@item.Naam" name="bestemmingKeuze" id="@item.Naam-Bestemming" type="radio" class="city-input"/>
            <span>@item.Naam</span>
        </label>
        }

</div>
<br />
<form asp-controller="Vlucht" asp-action="Index">
    <div class="date-fields">
        <div class="form-group">
            <label for="StartDate"></label>
                <input id="StartDate" name="StartDate" class="form-control" placeholder="Vertrekdatum"/> <!--readonly-->
        </div>
        <div class="form-group">
            <label for="EndDate"></label>
                <input id="EndDate" name="EndDate" class="form-control" placeholder="Vertrekdatum"/> <!--readonly-->
        </div>
    </div>



    <input type="hidden" name="Vertrek" value="" />
    <input type="hidden" name="Bestemming" value="" />
    <div class="buttonDiv">
        <button id="zieVluchtenLink">Zie vluchten</button>
    </div>
    
</form>
   
</div>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
         $(() => {
            let minDate = new Date();
            let maxDate = new Date();
			minDate.setDate(minDate.getDate() + 3);
			maxDate.setMonth(maxDate.getMonth() + 6);
            let mindate;
            $("#StartDate").datepicker({
                beforeShowDay: $.datepicker.noWeekends,
                minDate: minDate,
                numberOfMonths: 2,
                dateFormat: 'yy-mm-dd',
                onSelect: (minDateStr) => {

                    mindate = minDateStr; // Get selected date
                    
                    $("#EndDate").datepicker('option', 'minDate',
                        minDateStr || '0');// Set other min, default to today // don't use $("#dateBack").datepicker({ minDate: min || '0' }); only for  initialization
                }
            });

            $("#EndDate").datepicker({
                minDate: minDate,
                numberOfMonths: 3,
                maxDate: maxDate,
                dateFormat: 'yy-mm-dd',
                onSelect: (maxDateStr) => {
                    if (maxDateStr !== null) {
                        console.log(maxDateStr);
                        let start = new Date(mindate);
                        let end = new Date(maxDateStr);
                        let days = (end - start)
                            / (1000 * 60 * 60 * 24);
                        
                        $("#DateResult").val(days);
                    }
                }
            });
        });
    </script>
}

<script>
    document.addEventListener("DOMContentLoaded",() => {
        var link = document.getElementById("zieVluchtenLink");

        link.addEventListener("click", function (event) {
            // Zoek de geselecteerde vertrekplaats
            var vertrekRadio = document.querySelector('input[name="vertrekKeuze"]:checked');
            var bestemmingRadio = document.querySelector('input[name="bestemmingKeuze"]:checked');
            if (!vertrekRadio) {
                alert("Kies een vertrekplaats.");
                event.preventDefault(); // stop klikken als niks gekozen is
                return;
            }
            if (!bestemmingRadio) {
                alert("Kies een bestemming.");
                event.preventDefault(); // stop klikken als niks gekozen is
                return;
            }
            var vertrek = vertrekRadio.value;
            var bestemming = bestemmingRadio.value;

            if(vertrek == bestemming){
				alert("Vertrekplaats en bestemming zijn gelijk.");
				event.preventDefault(); // stop klikken als niks gekozen is
				return;
			}
             
                document.querySelector("input[name='Vertrek']").value = vertrekRadio.value;
                document.querySelector("input[name='Bestemming']").value = bestemmingRadio.value;
        });
    });
</script>