Airlines/Controllers/BoekingsController.cs
using Airlines.ViewModels;
using AutoMapper;
using Domains.Entities;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;

namespace Airlines.Controllers
{
    public class BoekingsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IPlaatsService _plaatsService;
        private readonly IVluchtService _vluchtService;
        public BoekingsController(IPlaatsService plaatsService, IVluchtService vluchtService, IMapper mapper)
        {
            _plaatsService = plaatsService;
            _vluchtService = vluchtService;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(string vertrek, string bestemming)
        {
            try
            {
                Console.WriteLine(vertrek);
                Console.WriteLine(bestemming);
                
                int vertrekPlaatsId = _plaatsService.GetByNaamAsync(vertrek).Result.PlaatsId;
                int bestemmingId = _plaatsService.GetByNaamAsync(bestemming).Result.PlaatsId;
                var lstVluchten = await _vluchtService.GetVluchtenTussenPlaatsen(vertrekPlaatsId, bestemmingId);
                
                List<VluchtVM> lstVluchtVM = null;
                if(lstVluchten != null)
                {
                    lstVluchtVM = _mapper.Map<List<VluchtVM>>(lstVluchten);
                    return View(lstVluchtVM);
                }
        
                
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Er is een fout opgetreden");
            }
            return View();
           
        }
    }
}

Airlines/Views/Shared/DisplayTemplates/_TilePlaatsView.cshtml
@model Airlines.ViewModels.PlaatsVM


@if(Model != null){
    
    <div class="card">
        <div class="content">

            <div class="back">
                <div class="back-content">
                    <strong class="countryNameCard">@Model.Naam</strong>
                </div>
            </div>

            <div class="front">
                <div class="front-content">
                    <p>Test</p>

                    <br/>
                    <br/>
                    <br/>
                    
                    <div class="description">
                        
                        
                        <form asp-controller="Boekings" asp-action="Index" method="get">
                            <input type="hidden" name="vertrekplaatsId" class="vertrekplaats-id" />
                            <input type="hidden" name="bestemmingId" value="@Model.Naam" />
                            <button type="submit">Boek nu</button>
                        </form>
                        
                    </div>
                </div>
            </div>

        </div>
    </div>
    
	@*
	<div class="col-md-4">
        <div class="tile">
			@Model.Naam
		</div>
	</div>
	*@
}