Airlines/Controllers/API/VluchtController.cs
using Airlines.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Interfaces;

namespace Airlines.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class VluchtController : Controller
    {
        private readonly IMapper _mapper;
        private IVluchtService _vluchtService;
        public VluchtController(IMapper mapper, IVluchtService vluchtService)
        {
            _mapper = mapper;
            _vluchtService = vluchtService;
        }
        [HttpGet]
        public async Task<ActionResult<VluchtVM>> GetVluchtenTussenPlaatsen(int vertrekPlaatdId, int bestemmingId)
        {
           var vluchten = await _vluchtService.GetVluchtenTussenPlaatsen(vertrekPlaatdId, bestemmingId);
            if (vluchten == null)
            {
                return NotFound("No flights found");
            }
            var vluchtenVMs = _mapper.Map<IEnumerable<VluchtVM>>(vluchten);
            return Ok(vluchtenVMs);
        }
    }
}

Airlines/Controllers/TicketController.cs
using Airlines.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;
using Airlines.Extensions;
namespace Airlines.Controllers
{
    public class TicketController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IReisklasseService _reisklasseService;
        private readonly IMaaltijdService _maaltijdService;
        private readonly ISeizoenService _seizoenService;
        private readonly IVluchtService _vluchtService;
        public TicketController(IMapper mapper, IReisklasseService reisklasseService, IMaaltijdService maaltijdService, ISeizoenService seizoenService, IVluchtService vluchtService)
        {
            _mapper = mapper;
            this._reisklasseService = reisklasseService;
            this._maaltijdService = maaltijdService;
            this._seizoenService = seizoenService;
            this._vluchtService = vluchtService;
        }
        
        public async Task<IActionResult> Index(VluchtVM vluchtVM)
        {

            try
            {
                var lstReisklassen = await _reisklasseService.GetAllAsync();
                var lstGewoneMaaltijden = await _maaltijdService.GetAllGewoneMaaltijdenAsync();
                var plaatsGebondenMaaltijd = await _maaltijdService.GetSpecifiekeMaaltijdVoorPlaats(vluchtVM.BestemmingNaam);
                TicketMogelijkhedenVM ticketMogelijkhedenVM = new TicketMogelijkhedenVM();
                if (lstReisklassen != null)
                {
                    ticketMogelijkhedenVM.Reisklassen = _mapper.Map<List<ReisklasseVM>>(lstReisklassen);
                }
                if (lstGewoneMaaltijden != null)
                {
                    ticketMogelijkhedenVM.Maaltijden = _mapper.Map<List<MaaltijdVM>>(lstGewoneMaaltijden);
                }
                if (plaatsGebondenMaaltijd != null)
                {
                    ticketMogelijkhedenVM.Maaltijden.Add(_mapper.Map<MaaltijdVM>(plaatsGebondenMaaltijd));
                }



                ticketMogelijkhedenVM.Vlucht = vluchtVM;
                var lstSeizoenen = await _seizoenService.GetAllAsync();
                if (lstSeizoenen != null)
                {
                    //gaat de seizoenen geven die in die perdio liggen
                    var tijdVertrek = vluchtVM.TijdVertrek;
                    var seizoen = lstSeizoenen.FirstOrDefault(s =>
                    {
                        var begin = new DateTime(1, s.BeginDatum.Month, s.BeginDatum.Day);
                        var eind = new DateTime(1, s.EindDatum.Month, s.EindDatum.Day);
                        var vertrek = new DateTime(1, tijdVertrek.Month, tijdVertrek.Day);

                        
                        return vertrek >= begin && vertrek <= eind;
                    });
                    //als geen seizoenen heeft gevonden doet die niets, anders voegt die dat toe aan de VM
                    if (seizoen != null)
                    {
                        ticketMogelijkhedenVM.Seizoen = _mapper.Map<SeizoenVM>(seizoen);
                    }
                }
               ticketMogelijkhedenVM.TotaalPrijs = vluchtVM.BeginPrijs;
                return View(ticketMogelijkhedenVM);

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Er is een fout opgetreden");
            }

            return View();
        }
        
        public async Task<IActionResult> VluchtSelecteren(TicketVM ticketVM, int maaltijdId, int reisklasseId , int vluchtId, int seizoenId)
        {
            try
            {
                var gekozenReisklasse = await _reisklasseService.GetByIdAsync(reisklasseId);
                var gekozenMaaltjd = await _maaltijdService.GetByIdAsync(maaltijdId);
                var vlucht = await _vluchtService.GetByIdAsync(vluchtId);
                if(seizoenId != 0)
                {
                    var seizoen = _seizoenService.GetByIdAsync(seizoenId);
                    ticketVM.Seizoen = _mapper.Map<SeizoenVM>(seizoen);
                }

                ticketVM.Reisklasse = _mapper.Map<ReisklasseVM>(gekozenReisklasse);
                ticketVM.Maaltijd = _mapper.Map<MaaltijdVM>(gekozenMaaltjd);
                ticketVM.Vlucht = _mapper.Map<VluchtVM>(vlucht);

                var shoppingCartVM = HttpContext.Session.GetObject<ShoppingCartVM>("ShoppingCart") ?? new ShoppingCartVM { Carts = new List<CartVM>() };

                shoppingCartVM.Carts.Add(new CartVM
                {
                    Ticket = ticketVM
                    
                });

                HttpContext.Session.SetObject("ShoppingCart", shoppingCartVM);
                return RedirectToAction("Index", "ShoppingCart");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Er is een fout opgetreden");
            }
            return View();
        }
        


    }
}

Airlines/Controllers/VluchtController.cs
using Airlines.ViewModels;
using AutoMapper;
using Domains.Entities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using Services.Interfaces;

namespace Airlines.Controllers
{
    public class VluchtController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IPlaatsService _plaatsService;
        private readonly IVluchtService _vluchtService;
        private readonly IZitplaatsService _zitplaatsService;
        public VluchtController(IPlaatsService plaatsService, IVluchtService vluchtService, IMapper mapper, IZitplaatsService zitplaatsService)
        {
            _plaatsService = plaatsService;
            _vluchtService = vluchtService;
            _mapper = mapper;
            _zitplaatsService = zitplaatsService;
        }
        [HttpPost]
        public async Task<IActionResult> Index(DateTime StartDate, DateTime EndDate, string vertrek, string bestemming)
        {
            try
            {
                Console.WriteLine(vertrek);
                Console.WriteLine(bestemming);
                
                int vertrekPlaatsId = _plaatsService.GetByNaamAsync(vertrek).Result.PlaatsId;
                int bestemmingId = _plaatsService.GetByNaamAsync(bestemming).Result.PlaatsId;

                var lstVluchten = await _vluchtService.GetNormaleVluchtenTussenPlaatsenTussenDatums(vertrekPlaatsId, bestemmingId, StartDate, EndDate);

                
                List<VluchtVM> lstVluchtVM = null;
                if(lstVluchten != null)
                {
                    lstVluchtVM = _mapper.Map<List<VluchtVM>>(lstVluchten);

                    List<VluchtMetOverstappenVM> lstVluchtMetOverstappenVM = new List<VluchtMetOverstappenVM>();
                    foreach (VluchtVM vlucht in lstVluchtVM)
                    {
                       VluchtMetOverstappenVM vluchtMetOverstappenVM = new VluchtMetOverstappenVM();
                        vluchtMetOverstappenVM.GewoneVlucht = vlucht;
                        var lstVanOverstapVluchten = await _vluchtService.GetOverstappenVanVlucht(vlucht.VluchtId);
                        vluchtMetOverstappenVM.OverstapVluchten = _mapper.Map<List<VluchtVM>>(lstVanOverstapVluchten);
                        var aantalBeschikbareZitplaatsen = await _zitplaatsService.TelAantalBeschikbareZitplaatsenVoorVlucht(vlucht.VluchtId);

                       vluchtMetOverstappenVM.AantalBeschikbarePlaatsen = aantalBeschikbareZitplaatsen;

                        lstVluchtMetOverstappenVM.Add(vluchtMetOverstappenVM);  
                    }



                    return View(lstVluchtMetOverstappenVM);

                }
                


            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Er is een fout opgetreden");
            }
            return View();
           
        }
    }
}

Airlines/Views/Vlucht/Index.cshtml
@model IEnumerable<Airlines.ViewModels.VluchtMetOverstappenVM>

@{
    ViewData["Title"] = "Index";
}


<link rel="stylesheet" href="/css/vluchten.css" asp-append-version="true" />

        <div class="blokPagina">
            <h1>Vluchten:</h1>
            <p class="subtitelVluchten">Ontdek ons ruim aanbod (Gilwe on top)</p>

            <div class="alleVluchtenBlok">

                @foreach (var item in Model)
                {
                    <div class="vluchtKaart">
                <img src="/images/bestemmingen/@(item.GewoneVlucht.BestemmingNaam + ".jpg")" alt="@item.GewoneVlucht.BestemmingNaam" />
                        <div class="inhoudVanVlucht">
                    <h3>@item.GewoneVlucht.VertrekNaam -> @item.GewoneVlucht.BestemmingNaam</h3>
                            <div class="tijden">
                        <p>🕒@item.GewoneVlucht.TijdVertrek</p>
                        <p>🕒@item.GewoneVlucht.TijdAankomst</p>
                            </div>
                            <div class="overstappen">
                                @if(item.OverstapVluchten !=null){
                                    @foreach(var itemOverstap in item.OverstapVluchten){
                                        <p>✈️ Overstap: @itemOverstap.BestemmingNaam</p>
                                    }
                                }else{
                                    <p>✈️ Geen overstappen</p>
                                }
                                
                            </div>
                            <hr class="solid"><!--Kan blijkbaar zorgen voor mooie divider lijn zoals in swift-->
                            <div>
                        <p>🪑 @item.AantalBeschikbarePlaatsen</p>
                        <p>Beginprijs: @item.GewoneVlucht.BeginPrijs &euro;</p>
                            </div>
                            
                        </div>
                        <form asp-controller="Ticket" asp-action="Index" method="post">
                    <input type="hidden" name="VluchtId" value="@item.GewoneVlucht.VluchtId" />
                    <input type="hidden" name="BeginPrijs" value="@item.GewoneVlucht.BeginPrijs" />
                    <input type="hidden" name="TijdVertrek" value="@item.GewoneVlucht.TijdVertrek" />
                    <input type="hidden" name="TijdAankomst" value="@item.GewoneVlucht.TijdAankomst" />
                    <input type="hidden" name="VliegtuigNaam" value="@item.GewoneVlucht.VliegtuigNaam" />

                    <input type="hidden" name="AantalTotalePlaatsen" value="@item.GewoneVlucht.AantalTotalePlaatsen" />
                    <input type="hidden" name="AantalGewonePlaatsen" value="@item.GewoneVlucht.AantalGewonePlaatsen" />
                    <input type="hidden" name="AantalBusinessPlaatsen" value="@item.GewoneVlucht.AantalBusinessPlaatsen" />
                    <input type="hidden" name="AantalEconomyPlaatsen" value="@item.GewoneVlucht.AantalEconomyPlaatsen" />
                    <input type="hidden" name="VertrekNaam" value="@item.GewoneVlucht.VertrekNaam" />
                    <input type="hidden" name="OverstapNaam" value="@item.GewoneVlucht.IsOverstap" />
                    <input type="hidden" name="BestemmingNaam" value="@item.GewoneVlucht.BestemmingNaam" />
                    @if(item.AantalBeschikbarePlaatsen !=0){
                        <button type="submit" class="vluchtButton">Boek deze vlucht</button>
                    }else{
                        <button type="submit" class="vluchtButtonBezet">Vlucht is volgeboekt</button>
                    }
                        </form>
                    </div>
                    
                }

            </div>
        </div>
  